### ISSUE TITLE
Support for "2-legged" OAuth v1.0a?

### ISSUE THREAD

**Issue by jonoellis** [gsuitedevs/apps-script-oauth1#31]
I've been trying to get the code to work with an API which uses "2-legged" OAuth v1.0a - am I correct in saying that this authentication isn't supported? If it is, is there an example?
Thank you!

**Comment by erickoledadevrel** [comment]
Which OAuth provider are you trying to use? It's possible it could be supported.

**Comment by erickoledadevrel** [comment]
It looks Xero uses RSA-SHA1, so issue #30 would also be a blocker.

**Comment by learner2020** [comment]
I have same issue with Linkdex's API, maybe due to their poor API doc [here](url
https://api.linkdex.com/application.wadl.html), which uses HMAC-SHA1. I cannot find the end points to fill below
```
service.setAccessTokenUrl()
service.setRequestTokenUrl()
service.setAuthorizationUrl()
```
I also tried doing as your example of Yelp [here](https://github.com/gsuitedevs/apps-script-oauth1/blob/master/samples/Yelp.gs) but failed. 

I'm listening to your suggestion on a way to handle this. 

Thanks in advance,

**Comment by learner2020** [comment]
@erickoledadevrel hope this request could get your attention, any guidance is appreciated. Thanks.

**Comment by erickoledadevrel** [comment]
@eddaly - Although the Xero documentation claims that the private application flow is 2-legged, it really isn't. It's a 1-legged flow, which the library does support. I'm working to add support for the RSA-SHA1 signatures in PR #41.

@learner2020 - Likewise, the Linkdex API you linked to claims to use 2-legged OAuth, but it's really 1-legged. Don't set any of those URLs and don't call `hasAccess()`. Just setup the service and then use it's fetch method, as shown in the Semantics3 sample.

I have yet to find any APIs that use a true 2-legged flow, so closing this feature request. If you find a real case please let me know.
